/**
 * Vercel / CI: writes config.runtime.js from environment variables.
 * Set in Vercel → Project → Settings → Environment Variables.
 * Cloudflare R2 public URLs: use DREAMEVO_INTRO_VIDEO_URL, DREAMEVO_MEDIA_BASE_URL, etc.
 */
'use strict';

var fs = require('fs');
var path = require('path');

var outPath = path.join(__dirname, '..', 'config.runtime.js');

/** Env var name → window property (same name) */
var KEYS = [
  'DREAMEVO_API_BASE',
  'DREAMEVO_INTRO_VIDEO_URL',
  'DREAMEVO_MEDIA_BASE_URL',
  'DREAMEVO_STEMS_BASE_URL',
  'DREAMEVO_AMBIENT_URL',
  'DREAMEVO_TURNSTILE_SITE_KEY'
];

var lines = [
  '/* Auto-generated by scripts/vercel-build.js - do not edit */',
  '(function () {',
  "  'use strict';",
  '  if (typeof window === "undefined") return;'
];

var setCount = 0;
KEYS.forEach(function (key) {
  var val = process.env[key];
  if (val && String(val).trim()) {
    lines.push('  window.' + key + ' = ' + JSON.stringify(String(val).trim()) + ';');
    setCount++;
  }
});

lines.push('})();', '');

fs.writeFileSync(outPath, lines.join('\n') + '\n', 'utf8');
console.log('[vercel-build] Wrote config.runtime.js (' + setCount + ' env var(s) injected)');
